### ISSUE TITLE
Add support for 'box' macro

### ISSUE THREAD

**Issue by petrdvorak** [wultra/docucheck#41]
We should support a `box` macro that renders an [info banner](https://getbootstrap.com/docs/5.0/components/alerts/) of a specified type:

```md
<!-- begin box info -->
   Body of the box
<!-- end -->
```

... should translate to:

```
{% box info %}
   Body of the box
{% endbox %}`
```

**Comment by hvge** [comment]
Do we know a final list of box styles? The example shows `info`, but I guess there are more options. I would like to add a few examples to the documentation.

**Comment by petrdvorak** [comment]
@hvge The current list in the plugin is:

- info
- warning
- success
